FROM python:3.9.10
# FROM public.ecr.aws/z9l7k5x5/test-ecs:docker_app-test

ENV PYTHONUNBUFFERED 1
RUN mkdir /code
WORKDIR /code
ADD requirements.txt /code/
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
ADD . /code/