FROM python:3.9.10
# FROM public.ecr.aws/z9l7k5x5/test-ecs:docker_app-test

RUN apt-get update && \
    apt-get -y install gcc libmariadb-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
RUN /usr/local/bin/python -m pip install --upgrade pip
RUN pip install mysqlclient

COPY ./table_get.py /app/table_get.py

CMD python ./table_get.py